# Generated by Django 5.2.8 on 2025-11-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('botnet', 'Botnet'), ('ransomware', 'Ransomware'), ('exploit', 'Exploit')], max_length=50)),
                ('target', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(default='AlienVault OTX', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_threats', models.IntegerField(default=0)),
                ('malware_count', models.IntegerField(default=0)),
                ('phishing_count', models.IntegerField(default=0)),
                ('botnet_count', models.IntegerField(default=0)),
                ('ransomware_count', models.IntegerField(default=0)),
                ('exploit_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Threat Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('hash', 'File Hash')], max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('result_found', models.BooleanField(default=False)),
                ('threat_detected', models.BooleanField(default=False)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
            },
        ),
    ]
